name: Build templates
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
      CI_BASE_URL: "https://raw.githubusercontent.com/${{ github.repository }}/gh-build"
    steps:
    - uses: actions/checkout@v3

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts' 
    - name: Node Install
      run: npm ci
    - name: Node Build
      run: npm run build

    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git add .
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push -f origin develop:gh-build